spring:
  application:
    name: simple-velo-bike-parking-api
    description: "Simple api to get nearest velo parking"
    devlopers: "Burtsev Anatoly,  anatolyburtsev@yandex.ru"

velobikeurl:
  host: http://apivelobike.velobike.ru
#  path: /ride/parkings

---
spring.profiles: test

velobikeurl:
  host: http://localhost:4567
#  path: /ride/parkings
